### PR TITLE
Adds cfscrape to bypass Cloudflare's *I'm under attack protection*

### PR DESCRIPTION
**Pull request by zatarra**
I've noticed that the requests were broken and after further inspection I found that the culprit was Cloudflare "I'm under attack' protection.

Using cfscrape fixes the issue.

### CODE REVIEW

**Comment by iNoSec** [comment]
why you didnt pull it on the master branch?? taht resolve all problem for a lot of person!!!! thanks

**Comment by zatarra** [comment]
I'm not sure of what you meant by "pull it on the master branch"  :)

I've forked the project, updated the file accordingly and created a pull request to merge this to master which the owner/team needs to approve.

**Comment by D4Vinci** [comment]
I don't know what you are talking about !
Hacked-emails      -> Stopped their api
HaveIBeenPwned -> They have rate limiting that makes it must be a request every 1.5 sec

I solves both poblems already weeks ago in the new version, just wait for the new version it will become a framework not just a toolkit :smile:
It's my work and other reasons what makes me very slow on working on it and it's a huge idea (wrote 1500 lines till now only in the core and five modules)

**Comment by zatarra** [comment]
I was talking about this:

`res = req.json()`

Instead of returning a valid json it was getting an HTML page from cloudflare with the "I'm under attack" protection which obviously was causing an exception. The PR solves this. 

But like you said, if the hacked-emails was shut down then I think you can ignore this PR :)

**Pull request closed without merging**
