### PR TITLE
Workaround for Cloudflare DDoS protection

### PR DESCRIPTION
**Pull request by mjwhitta**
I also added a `-d` option to not prompt for passwords. I may have also updated some comments. Feel free to pick and choose any changes you would like.

### CODE REVIEW

**Comment by mjwhitta** [comment]
I didn't see the other pull request till just now. We both used `cfscrape`, so again, feel free to pick and choose or just close.

**Review by codingo — APPROVED** [review]

**Comment by codingo** [comment]
I had a need for this so pulled it into my own project. Couldn't find the other instance referenced in this pr (have an id @mjwhitta?).  Code is good and does as described.

**Comment by mjwhitta** [comment]
@codingo: Sorry, the other pull request was #70 .

**Comment by codingo** [comment]
Ahh, I looked at closed/merged, didn't think to check it was still open. Makes sense. Up to @D4Vinci how to approach then.

**Review by hazael00 — APPROVED** [review]

**Review by naami2004 — APPROVED** [review]

**Pull request closed without merging**
